### ISSUE TITLE
Revisen el nombre del proyecto y de la base de datos

### ISSUE THREAD

**Issue by fmachadopiriz** [ucudal/pii_2019_equipo2#22]
Tengan en cuenta que Mvc es la tecnología y no representa el producto que están construyendo

**Comment by SanGar03** [comment]
Cambiamos el nombre de la base de datos, pero no sabemos a que te referis con revisar el nombre del proyecto.

**Comment by fmachadopiriz** [comment]
Esto quedó bien con los cambios que hicieron
